version: 1.0.{build}
before_build:
  - nuget restore ".\SafeMapper.sln"  
build:
  project: .\SafeMapper.sln
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: '*.nupkg'
  name: Nuget
environment:
    COVERALLS_REPO_TOKEN:  
       secure: K+fCPAUxXxW0g4oxV+/Y8oYyiiYKagU4gOQ9SRP5AH9Si3uACrS4D1kKxOsXs/Bp
after_test:
    - packages\OpenCover.4.5.3522\OpenCover.Console.exe -register:user "-target:packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" "-targetargs:SafeMapper.Tests\bin\Debug\SafeMapper.Tests.dll /noshadow /xml=TestResult.xml" "-filter:+[SafeMapper*]* -[SafeMapper.Tests*]*" "-output:opencovertests.xml"
    - packages\coveralls.net.0.5.0\csmacnz.Coveralls.exe --opencover -i opencovertests.xml --repoToken %COVERALLS_REPO_TOKEN% --commitId %APPVEYOR_REPO_COMMIT% --commitBranch %APPVEYOR_REPO_BRANCH% --commitAuthor %APPVEYOR_REPO_COMMIT_AUTHOR% --commitEmail %APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL% --commitMessage %APPVEYOR_REPO_COMMIT_MESSAGE% --jobId %APPVEYOR_JOB_ID%