version: 1.3.{build}
configuration: Release
nuget:
  account_feed: true
init:
  - git config --global core.autocrlf true
install:
 - cmd: nuget sources add -Name api.nuget.org -Source https://api.nuget.org/v3/index.json
before_build:
 - ps: "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
 - ps: dnvm install 1.0.0-beta7
 - ps: dnvm upgrade
 - ps: dnvm update-self
 - ps: dnvm list
 - ps: dnvm use 1.0.0-beta7
 - ps: npm cache clean
 - ps: npm install -g gulp bower
 - ps: dnu restore
# Use NuGet 2.*
 - ps: (New-Object Net.WebClient).DownloadFile('https://www.nuget.org/nuget.exe', 'C:\Tools\NuGet\NuGet.exe')
 - ps: nuget restore
 - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
build:
  project: .\SafeMapper.sln
  publish_nuget: true
  verbosity: minimal
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
artifacts:
- path: '*.nupkg'
  name: Nuget
environment:
    COVERALLS_REPO_TOKEN:  
       secure: K+fCPAUxXxW0g4oxV+/Y8oYyiiYKagU4gOQ9SRP5AH9Si3uACrS4D1kKxOsXs/Bp
after_test:
    - packages\OpenCover.4.5.3522\OpenCover.Console.exe -register:user "-target:packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" "-targetargs:SafeMapper.Tests\bin\%CONFIGURATION%\SafeMapper.Tests.dll /noshadow" "-filter:+[SafeMapper*]* -[SafeMapper.Tests*]*" -output:coverage.xml
    - packages\coveralls.io.1.1.91\tools\coveralls.net.exe --opencover coverage.xml