version: 1.0.{build}
before_build:
  - nuget restore ".\SafeMapper.sln"  
configuration: Release
build:
  project: .\SafeMapper\SafeMapper.csproj
  publish_nuget: true
  verbosity: minimal
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
artifacts:
- path: '*.nupkg'
  name: Nuget
environment:
    COVERALLS_REPO_TOKEN:  
       secure: K+fCPAUxXxW0g4oxV+/Y8oYyiiYKagU4gOQ9SRP5AH9Si3uACrS4D1kKxOsXs/Bp
after_test:
    - packages\OpenCover.4.5.3522\OpenCover.Console.exe -register:user "-target:packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" "-targetargs:SafeMapper.Tests\bin\%CONFIGURATION%\SafeMapper.Tests.dll /noshadow" "-filter:+[SafeMapper*]* -[SafeMapper.Tests*]*" -output:coverage.xml
    - packages\coveralls.io.1.1.91\tools\coveralls.net.exe --opencover coverage.xml